name: kontena
description: "Kɔntena - Offline-first indigenous language mesh data platform"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.3.3
  uuid: ^4.4.0
  path: ^1.9.0
  intl: ^0.19.0
  http: ^1.2.1
  connectivity_plus: ^6.0.3
  flutter_blue_plus: ^1.31.5
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
